## Copyright © 2021, Oracle and/or its affiliates.
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

    title: "Cloud Backup with RClone"
    stackDescription: "Deploy the required infrastructure to use Object storage for backup with RClone"
    schemaVersion: 1.1.0
    version: "20190404"
    locale: "en"

    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid
      - source_file
      - lifecycle_policy_archive_rule_name
      - lifecycle_policy_abort_rule_name

    - title: Required Configuration
      visible: true
      variables:
      - compartment_ocid
      - region
      - bucket_name
      - lifecycle_policy_archive_rule_is_enabled
      - lifecycle_policy_abort_rule_is_enabled
      - show_advanced

    - title: Bucket Configuration
      visible: 
        and:
          - show_advanced
      variables:
      - bucket_access_type
      - bucket_storage_tier
 
    - title: OSS Bucket Lifecycle Archive Policy Configuration
      visible: 
        and:
          - show_advanced
      variables:
      - lifecycle_policy_archive_rule_time_amount
      - lifecycle_policy_archive_rule_time_unit
      - lifecycle_policy_archive_rule_inclusion_prefixes
      - lifecycle_policy_archive_rule_target

    - title: OSS Bucket Lifecycle Abort Policy Configuration
      visible: 
        and:
          - show_advanced
      variables:
      - lifecycle_policy_abort_rule_time_amount
      - lifecycle_policy_abort_rule_time_unit
      - lifecycle_policy_abort_rule_target

    - title: IAM Configuration
      visible: 
        and:
          - show_advanced
      variables:
      - group_name
      - group_description
      - policy_name
      - policy_description
      - backupuser_name
      - secret_key_name

    variables:

      show_advanced:
        type: boolean
        title: "Show advanced options?"
        description: "Shows advanced options."
        visible: true
        default: false

      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        title: Compartment
        description: Compartment where you want to create the solution resources

      region:
        type: oci:identity:region:name
        required: true
        title: Region
        description: Region where you want to deploy the resources defined by this stack

      bucket_name:
        type: string
        required: true
        title: "Bucket Name"
        description: "Name of the bucket"

      bucket_access_type:
        type: enum
        required: true
        title: "Access Type"
        description: "Choose the type of access for the backup bucket"
        enum:
          - "NoPublicAccess"
          - "Public"
        default: "NoPublicAccess"

      bucket_storage_tier:
        type: enum
        required: true
        title: "Storage Tier"
        description: "Select the tier for the backup bucket"
        enum:
          - "Standard"
          - "Archive"
        default: "Standard"

      group_name:
        type: string
        required: true
        title: "Group Name"
        description: "Name of the backup group"

      group_description:
        type: string
        required: true
        title: "Group Description"
        description: "Backup Group Description"

      policy_name:
        type: string
        required: true
        title: "Policy Name"
        description: "Backup Policy name"

      policy_description:
        type: string
        required: true
        title: "Policy Description"
        description: "Description of the policy"

      backupuser_name:
        type: string
        required: true
        title: "Username"
        description: "Username of the account used for backup"

      secret_key_name:
        type: string
        required: true
        title: "Secret Key Name"
        description: "Secret Key Name for the account used for backup"
        default: "IAMUserSecretKey4OSS"


      lifecycle_policy_archive_rule_is_enabled:
        type: boolean
        title: "Enable Bucket Archive Lifecycle Policy Rule?"
        description: "Check if you want to enable Bucket Archive Lifecycle Policy Rule."
        required: true
        visible: true
        default: true

      lifecycle_policy_archive_rule_time_amount:
        visible: 
          and:
            - lifecycle_policy_archive_rule_is_enabled
        type: number
        minimum: 1
        maximum: 128
        multipleOf: 1
        default: 10
        required: false
        title: "Archive - Time Amount"
        description: "Bucket Archive Lifecycle Polocy Rule - Time Amount"

      lifecycle_policy_archive_rule_time_unit:
        visible: 
          and:
            - lifecycle_policy_archive_rule_is_enabled
        type: enum
        title: "Archive - Time Unit"
        description: "Bucket Archive Lifecycle Polocy Rule - Time Amount"
        enum:
          - "DAYS"
          - "YEARS"
        default: "DAYS"

      lifecycle_policy_archive_rule_inclusion_prefixes:
        visible: 
          and:
            - lifecycle_policy_archive_rule_is_enabled
        type: string
        title: "Archive - Inclusion Prefix"
        description: "Archive - Inclusion Prefix"

      lifecycle_policy_archive_rule_target:
        visible: 
          and:
            - lifecycle_policy_archive_rule_is_enabled
        type: enum
        title: "Archive - Target"
        description: "Bucket Archive Lifecycle Polocy Rule - Target"
        enum:
          - "objects"
          - "multipart-uploads"
        default: "objects"        

      lifecycle_policy_abort_rule_is_enabled:
        type: boolean
        title: "Enable Bucket Abort Lifecycle Policy Rule?"
        description: "Check if you want to enable Bucket Abort Lifecycle Policy Rule."
        visible: true
        default: true
        required: true

      lifecycle_policy_abort_rule_time_amount:
        visible: 
          and:
            - lifecycle_policy_abort_rule_is_enabled
        type: number
        minimum: 1
        maximum: 128
        multipleOf: 1
        default: 10
        title: "Abort - Time Amount"
        description: "Bucket Abort Lifecycle Polocy Rule - Time Amount"

      lifecycle_policy_abort_rule_time_unit:
        visible: 
          and:
            - lifecycle_policy_abort_rule_is_enabled
        type: enum
        title: "Abort - Time Unit"
        description: "Bucket Abort Lifecycle Polocy Rule - Time Unit"
        enum:
          - "DAYS"
          - "YEARS"
        default: "DAYS"

      lifecycle_policy_abort_rule_target:
        visible: 
          and:
            - lifecycle_policy_abort_rule_is_enabled
        type: enum
        title: "Abort - Target"
        description: "Bucket Abort Lifecycle Polocy Rule - Target"
        enum:
          - "objects"
          - "multipart-uploads"
        default: "multipart-uploads" 

